package ai.mymanus.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for Message model
 * Tests message creation and validation
 */
class MessageTest {

    private Message message;

    @BeforeEach
    void setUp() {
        message = new Message();
    }

    @Test
    void testMessageCreation() {
        message.setSessionId("test-session");
        message.setRole(Message.Role.USER);
        message.setContent("Hello, agent!");

        assertNotNull(message);
        assertEquals("test-session", message.getSessionId());
        assertEquals(Message.Role.USER, message.getRole());
        assertEquals("Hello, agent!", message.getContent());
    }

    @Test
    void testUserMessage() {
        message.setRole(Message.Role.USER);
        message.setContent("Please read the file");

        assertEquals(Message.Role.USER, message.getRole());
        assertEquals("Please read the file", message.getContent());
    }

    @Test
    void testAssistantMessage() {
        message.setRole(Message.Role.ASSISTANT);
        message.setContent("I'll read the file for you");

        assertEquals(Message.Role.ASSISTANT, message.getRole());
        assertEquals("I'll read the file for you", message.getContent());
    }

    @Test
    void testSystemMessage() {
        message.setRole(Message.Role.SYSTEM);
        message.setContent("You are a helpful AI agent");

        assertEquals(Message.Role.SYSTEM, message.getRole());
        assertEquals("You are a helpful AI agent", message.getContent());
    }

    @Test
    void testAllRoles() {
        Message.Role[] allRoles = Message.Role.values();

        // Verify all 3 roles exist
        assertEquals(3, allRoles.length);

        assertTrue(containsRole(allRoles, Message.Role.USER));
        assertTrue(containsRole(allRoles, Message.Role.ASSISTANT));
        assertTrue(containsRole(allRoles, Message.Role.SYSTEM));
    }

    @Test
    void testEmptyContent() {
        message.setContent("");
        assertEquals("", message.getContent());
    }

    @Test
    void testNullContent() {
        message.setContent(null);
        assertNull(message.getContent());
    }

    @Test
    void testLongContent() {
        String longContent = "a".repeat(10000);
        message.setContent(longContent);
        assertEquals(10000, message.getContent().length());
    }

    @Test
    void testMessageWithNewlines() {
        String multilineContent = "Line 1\nLine 2\nLine 3";
        message.setContent(multilineContent);
        assertEquals(multilineContent, message.getContent());
        assertTrue(message.getContent().contains("\n"));
    }

    @Test
    void testMessageWithSpecialCharacters() {
        String specialContent = "Hello 世界! 🌍 <>&\"'";
        message.setContent(specialContent);
        assertEquals(specialContent, message.getContent());
    }

    @Test
    void testSessionIdAssociation() {
        message.setSessionId("session-123");
        assertEquals("session-123", message.getSessionId());

        message.setSessionId("session-456");
        assertEquals("session-456", message.getSessionId());
    }

    @Test
    void testTimestampGeneration() {
        long beforeTime = System.currentTimeMillis();

        // Simulate timestamp setting (would be auto-generated by JPA)
        message.setCreatedAt(new java.util.Date());

        long afterTime = System.currentTimeMillis();

        assertNotNull(message.getCreatedAt());
        assertTrue(message.getCreatedAt().getTime() >= beforeTime);
        assertTrue(message.getCreatedAt().getTime() <= afterTime);
    }

    private boolean containsRole(Message.Role[] roles, Message.Role target) {
        for (Message.Role role : roles) {
            if (role == target) return true;
        }
        return false;
    }
}
